name: Build and Deploy to Firebase Hosting

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '7.0.x'

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet publish -c Release -o ./publish

    - name: Deploy to Firebase Hosting
      uses: w9jds/firebase-action@master
      with:
        args: deploy --only hosting
      env:
        FIREBASE_TOKEN: $1//09q9ON_DhZjUBCgYIARAAGAkSNwF-L9IrU6HEUG1LVDALN11S2_atjKnoR4RxsYPeZ0OcKiHxS7Ypv70e-vHqxBAUoQTxkAF01rs
